library(shiny)

# Define UI for slider demo application
shinyUI(pageWithSidebar(

  #  Application title
  headerPanel("EDC - Consolidated"),

  # Sidebar with sliders that demonstrate various available options
   tabsetPanel(
		tabPanel("Extensification",
			tabsetPanel(
				tabPanel("BU-Monthly-Acquisition",
				sidebarPanel(
					selectInput("category","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE),
					tags$head(
						tags$style(type="text/css", "select { width: 200px; }"),
						tags$style(type="text/css", "textarea { max-width: 85px; }"),
						tags$style(type="text/css", ".jslider { max-width: 200px; }"),
						tags$style(type='text/css', ".well { max-width: 230px; }"),
						tags$style(type='text/css', ".span4 { max-width: 230px; }"))
					),htmlOutput("Ex1")),
				tabPanel("BU - by Merchant Cat",
				sidebarPanel(
					selectInput("period2","SELECT PERIOD",c(	"January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
					selectInput("type2","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
					htmlOutput("Ex2")),
				tabPanel("Portfolio-Acquisition Movement",
				sidebarPanel(
					selectInput("category","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE),
					selectInput("region","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE)),
					tags$head(
						tags$style(type="text/css", "select { width: 200px; }"),
						tags$style(type="text/css", "textarea { max-width: 85px; }"),
						tags$style(type="text/css", ".jslider { max-width: 200px; }"),
						tags$style(type='text/css', ".well { max-width: 230px; }"),
						tags$style(type='text/css', ".span4 { max-width: 230px; }")),
					plotOutput(outputId = "Ex3", height = "500px", width="500px")),
				tabPanel("Acquisition-performance tracker",
				sidebarPanel(
					selectInput("category4","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type4","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE),
					selectInput("region4","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE)),
					htmlOutput("Ex4")),
				tabPanel("Daily Trend Acquisition",
				sidebarPanel(
					selectInput("category5","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type5","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE),
					selectInput("region5","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE)),
					htmlOutput("Ex5"))
			)),
		tabPanel("Intensification",
			tabsetPanel(
				tabPanel("BU - Monthly - Throughput Track",
				sidebarPanel(
					selectInput("category6","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type6","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
				htmlOutput("In1")),
				tabPanel("Consolidated Monthly Score Card",
					tabsetPanel(
						tabPanel("Profitability",
							sidebarPanel(
								selectInput("period7","SELECT PERIOD",c("January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
								selectInput("category7","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
								selectInput("type7","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
						
							htmlOutput("In2")),
						tabPanel("Portfolio & Net Addition",
							sidebarPanel(
								selectInput("period8","SELECT PERIOD",c(	"January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
								selectInput("category8","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
								selectInput("type8","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
							htmlOutput("In3")),
						tabPanel("Usage",
							sidebarPanel(
								selectInput("period9","SELECT PERIOD",c(	"January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
								selectInput("category9","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
								selectInput("type9","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
							htmlOutput("In4"))
								)),
				tabPanel("Merchant Category Performance",
				tabsetPanel(
						tabPanel("Profitability",
							sidebarPanel(
								selectInput("period10","SELECT PERIOD",c("January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
								selectInput("region10","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE),
								selectInput("type10","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
						
							htmlOutput("In5")),
						tabPanel("Portfolio & Net Addition",
							sidebarPanel(
								selectInput("period11","SELECT PERIOD",c(	"January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
								selectInput("region11","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE),
								selectInput("type11","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
							htmlOutput("In6")),
						tabPanel("Usage",
							sidebarPanel(
								selectInput("period12","SELECT PERIOD",c(	"January"="January",
															"February"="February",
															"March"="March",
															"April"="April",
															"May"="May",
															"June"="June",
															"July"="July",
															"August"="August",
															"September"="September",
															"October"="October",
															"November"="November"),selected="January",multiple=TRUE),
								selectInput("region12","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE),
								selectInput("type12","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE)),
							htmlOutput("In7"))
				)),
				tabPanel("Daily Trend",
					sidebarPanel(
					selectInput("category13","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type13","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE),
					selectInput("region13","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE)),
					htmlOutput("In8"))
			)),
		tabPanel("Actionable",
			tabsetPanel(
				tabPanel("Actionables Summary",
				sidebarPanel(
					selectInput("category14","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=TRUE),
					selectInput("type14","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=TRUE),
					selectInput("region14","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=TRUE)),
				htmlOutput("Ac1")),
				tabPanel("Actionables Report",
				sidebarPanel(
					selectInput("category15","SELECT MERCHANT",c("Retail Store"="Retail Store",
																"Kirana Store"="Kirana Store",
																"Hotels"="Hotels",
																"Restaurants"="Restaurants",
																"Airline"="Airline",
																"Hardware Store"="Hardware Store",
																"Computer Store"="Computer Store",
																"Gaming Zone"="Gaming Zone",
																"Super Market"="Super Market",
																"Fast Food Centre"="Fast Food Centre"),selected="Retail Store",multiple=FALSE),
					selectInput("type15","SELECT MERCHANT TYPE",c("RETAIL"="retail",
																"HOLDING"="holding"),selected="RETAIL",multiple=FALSE),
					selectInput("region15","SELECT REGION",c("REGION1"="Region1",
															"REGION2"="Region2",
															"REGION3"="Region3",
															"REGION4"="Region4",
															"REGION5"="Region5",
															"REGION6"="Region6",
															"REGION7"="Region7",
															"REGION8"="Region8",
															"REGION9"="Region9",
															"REGION10"="Region10"),selected="REGION1",multiple=FALSE)),
				htmlOutput("Ac2"))
				))
			),
  # Show a table summarizing the values entered
  mainPanel()
))
